### ISSUE TITLE
removeMarker works very slowly when removing a lot of markers

### ISSUE THREAD

**Issue by benderlidze** [francoisromain/leaflet-markers-canvas#6]
Thank you for your lib, it is great. 
addMarkers is fast, 
is it possible to add something like removeMarkerS since removeMarker is slow when trying to delete 10k markers by one 
As I find out this part makes it slow
```
 if (isVisible) {
          this._redraw(true);
        }
```
Thanks

**Comment by francoisromain** [comment]
Hello 
there is already a clear function to remove all the markers. Does it work for your case?

**Comment by benderlidze** [comment]
I need to remove a part of markers, for example, 10k from 20k or so. I don't want to remove all markers

**Comment by francoisromain** [comment]
ok. 
Do you want to make a PR?

**Comment by francoisromain** [comment]
I made something in the PR above but I didn't try. Could you see if it works please?

**Comment by benderlidze** [comment]
Yes, this works fine for me. Thank you!
